gelweb/gel2mdt/urls.py
"""Copyright (c) 2018 Great Ormond Street Hospital for Children NHS Foundation
Trust & Birmingham Women's and Children's NHS Foundation Trust

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from .api.api_urls import *

urlpatterns = [
    path('', views.index, name='index'),

    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/remove_case/<int:case_id>', views.remove_case, name='remove-case'),
    path('cancer-main', views.cancer_main, name='cancer-main'),
    path('rare-disease-main', views.rare_disease_main, name='rare-disease-main'),
    path('gel2me/', RedirectView.as_view(url='/', permanent=False), name='gel2me'),
    path('proband/<int:report_id>', views.proband_view, name='proband-view'),
    path('edit_relative/<int:relative_id>', views.edit_relatives, name='edit-relatives'),
    path('pull_t3_variants/<int:report_id>', views.pull_t3_variants, name='pull-t3-variants'),
    path('proband/<int:report_id>/report/<str:outcome>', views.report, name='report'),
    path('update_proband/<int:report_id>', views.update_proband, name='update-proband'),
    path('update_demographics/<int:report_id>', views.update_demographics, name='update-demographics'),
    path('ajax_validation', views.ajax_variant_validation, name='ajax_validation'),
    path('<str:sample_type>/validation_list', views.validation_list, name='validation-list'),

    path('variant/<int:variant_id>', views.variant_view, name='variant-view'),

    path('panel/<int:panelversion_id>', views.panel_view, name='panel'),

    path('select_transcript/<int:report_id>/<int:pv_id>', views.select_transcript, name='select-transcript'),
    path('update_transcript/<int:report_id>/<int:pv_id>/<int:transcript_id>', views.update_transcript,
         name='update-transcript'),

    path('<str:sample_type>/start_mdt/', views.start_mdt_view, name='start-mdt'),
    path('<str:sample_type>/edit_mdt/<int:mdt_id>', views.edit_mdt, name='edit-mdt'),
    path('mdt_view/<int:mdt_id>', views.mdt_view, name='mdt-view'),
    path('mdt_proband_view/<int:mdt_id>/<int:pk>/<int:important>', views.mdt_proband_view, name='mdt-proband-view'),

    path('add_ir_to_mdt/<int:mdt_id>/<int:irreport_id>', views.add_ir_to_mdt, name='add-ir-to-mdt'),
    path('remove_ir_from_mdt/<int:mdt_id>/<int:irreport_id>', views.remove_ir_from_mdt, name='remove-ir-from-mdt'),

    path('edit_mdt_proband/<int:report_id>', views.edit_mdt_proband, name='edit-mdt-proband'),

    path('<str:sample_type>/recent_mdts/', views.recent_mdts, name='recent-mdt'),

    path('delete_mdt/<int:mdt_id>', views.delete_mdt, name='delete-mdt'),
    path('export_mdt/<int:mdt_id>', views.export_mdt, name='export-mdt'),
    path('export_mdt_outcome_form/<int:report_id>', views.export_mdt_outcome_form, name='export-mdt-outcome'),

    path('select_attendees_for_mdt/<int:mdt_id>', views.select_attendees_for_mdt, name='select-attendees-for-mdt'),
    path('add_attendee_to_mdt/<int:mdt_id>/<int:attendee_id>/<str:role>', views.add_attendee_to_mdt,
         name='add-attendee-to-mdt'),
    path('remove_attendee_from_mdt/<int:mdt_id>/<int:attendee_id>/<str:role>', views.remove_attendee_from_mdt,
         name='remove-attendee-from-mdt'),
    path('add_new_attendee/', views.add_new_attendee, name='add-new-attendee'),

    path(r'genomics_england_report/<int:report_id>', views.genomics_england_report, name='genomics-england-report'),
    path('<str:sample_type>/audit/', views.audit, name='audit'),
    path('<str:sample_type>/gene_search/', views.search_by_gene, name='gene_search'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

urlpatterns += api_urlpatterns

gelweb/gelweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gel2mdt.urls')),
    path('clinician/', include(('gel2clin.urls', 'gel2clin'), namespace='gel2clin')),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout', kwargs={'next_page': '/'}),



]

gelweb/gel2mdt/models.py
"""Copyright (c) 2018 Great Ormond Street Hospital for Children NHS Foundation
Trust & Birmingham Women's and Children's NHS Foundation Trust

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
from django.db import models
from django.utils import timezone
from django.conf import settings

import pandas as pd

from .model_utils.choices import ChoiceEnum
from .config import load_config


class ListUpdate(models.Model):
    """
    A table containing a single field which displays the each time the
    results list was updated.
    """
    update_time = models.DateTimeField()
    success = models.BooleanField()

    cases_added = models.IntegerField()
    cases_updated = models.IntegerField()

    error = models.TextField(null=True)

    class Meta:
        managed = True
        db_table = 'ListUpdate'
        app_label= 'gel2mdt'


class ToolOrAssemblyVersion(models.Model):
    """
    Represents a tool used or genome build and version used in several use cases
    within the CIP workflow.
    """
    class Meta:
        verbose_name_plural = "Tool and assembly versions"
        managed = True
        db_table = 'ToolOrAssemblyVersion'
        app_label= 'gel2mdt'

    tool_name = models.CharField(max_length=200)
    version_number = models.CharField(max_length=200)

    def __str__(self):
        return str(self.version_number)


class Phenotype(models.Model):
    description = models.CharField(max_length=200, null=True, blank=True)
    hpo_terms = models.CharField(max_length=200)

    def __str__(self):
        return str(self.description)

    class Meta:
        managed = True
        db_table = 'Phenotype'
        app_label= 'gel2mdt'


class Clinician(models.Model):
    name = models.CharField(max_length=200)
    hospital = models.CharField(max_length=200)
    email = models.EmailField()
    added_by_user = models.BooleanField(default=False)
    relates_to = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        managed = True
        db_table = 'Clinician'
        app_label= 'gel2mdt'


class Family(models.Model):
    """
    Represents a family within the CIP API: proband and relatives (if present)
    link to a particular family. Holds information about which panels have been
    applied to this case, which should be concordant with the phenotype of the
    proband.
    """
    class Meta:
        verbose_name_plural = "Families"
        db_table = 'Family'
        managed = True
        app_label= 'gel2mdt'
    gel_family_id = models.CharField(max_length=200, unique=True)

    clinician = models.ForeignKey(Clinician, on_delete=models.CASCADE)
    trio_sequenced = models.BooleanField()
    has_de_novo = models.BooleanField()

    def __str__(self):
        return str(self.gel_family_id)


class FamilyPhenotype(models.Model):
    """
    A linkage table for Family and Phenotype.
    """
    class Meta:
        managed = True
        db_table='FamilyPhenotype'
        app_label= 'gel2mdt'

    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    phenotype = models.ForeignKey(Phenotype, on_delete=models.CASCADE)


class Gene(models.Model):
    """
    Represents an individual gene. Whilst HGNC names may change, use of the
    Ensembl ID hopes to be able to reference any gene consistently despite
    future name changes - the ENSG should not change.
    """
    ensembl_id = models.CharField(max_length=200)
    hgnc_name = models.CharField(max_length=200)
    hgnc_id = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return str(self.hgnc_name)

    class Meta:
        managed = True
        db_table = 'Gene'
        app_label= 'gel2mdt'


class Panel(models.Model):
    """
    Represents a panel from panelApp which should be the panels used by GeL.
    Holds information about the relevant diseases.
    """
    panel_name = models.CharField(max_length=200)
    panelapp_id = models.CharField(max_length=200, unique=True)
    disease_group = models.CharField(max_length=200)
    disease_subgroup = models.CharField(max_length=200)

    def __str__(self):
        return str(self.panel_name)

    class Meta:
        managed = True
        db_table = 'Panel'
        app_label= 'gel2mdt'


class PanelVersion(models.Model):
    """
    Represents a version of a panel: holds a version number and list of
    genes for panel. Genes are listed here since they may change with each
    version.
    """
    panel = models.ForeignKey(Panel, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=200)

    def __str__(self):
        return str(self.panel.panel_name + ' v' + self.version_number)

    class Meta:
        managed = True
        db_table = 'PanelVersion'
        app_label= 'gel2mdt'


class PanelVersionGene(models.Model):
    """
    Linkage table to relate Panels and Genes via a Many to Many relationship
    which is still compatible with the MultipleCaseAdder.
    """
    class Meta:
        managed = True
        app_label= 'gel2mdt'

    panel_version = models.ForeignKey(PanelVersion, on_delete=models.CASCADE)
    gene = models.ForeignKey(Gene, on_delete=models.CASCADE)

    level_of_confidence = models.CharField(max_length=200)


class InterpretationReportFamily(models.Model):
    """
    Acts as a container for all of the data for a particular report
    as it moves through the CIP workflow, allowing us to see how the
    data has changed as the status changes.
    """
    class Meta:
        verbose_name_plural = "Interpretation report families"
        managed = True
        db_table = 'InterpretationReportFamily'
        app_label= 'gel2mdt'

    ir_family_id = models.CharField(max_length=10, unique=True)
    participant_family = models.ForeignKey(
        Family, on_delete=models.CASCADE, null=True)

    priority = models.CharField(max_length=200)
    # some fields nullable to allow bulk saving before Panel and Family objects added

    # TODO: add choices once known. so far, I know of:
    # - omicia
    # - congenica
    # - nextcode
    # but there are probably more. need to be sure before choices added
    cip = models.CharField(max_length=200)

    # hash allows quicker determination of difference between reports
    # sha_hash = models.CharField(max_length=200)

    def __str__(self):
        return str(self.ir_family_id)


class InterpretationReportFamilyPanel(models.Model):
    """
    Linkages table to connect IRF with a Panel to allow M2M relationships
    that are still amenable to addition via the MCA.
    """
    class Meta:
        managed=True
        app_label= 'gel2mdt'

    ir_family = models.ForeignKey(InterpretationReportFamily, on_delete=models.CASCADE)
    panel = models.ForeignKey(PanelVersion, on_delete=models.CASCADE)

    custom = models.BooleanField(default=False)

    average_coverage = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    proportion_above_15x = models.DecimalField(max_digits=6, decimal_places=5, null=True)

    genes_failing_coverage = models.TextField(null=True)


class GELInterpretationReportQuerySet(models.QuerySet):
    def latest_cases_by_sample_type(self, sample_type):
        qs = self.filter(sample_type=sample_type)
        qs_df = pd.DataFrame(list(qs.values())).sort_values(
            by=["ir_family_id", "archived_version"]
        )
        rm_dup_old = qs_df.drop_duplicates(
            subset=["ir_family_id"],
            keep="last"
        )
        ids_of_latest_cases = rm_dup_old["id"].tolist()
        return self.filter(id__in=ids_of_latest_cases)

    def latest_cases_by_user(self, username):
        qs = self.filter(assigned_user__username=username)
        if qs:
            qs_df = pd.DataFrame(list(qs.values())).sort_values(
                by=["ir_family_id", "archived_version"]
            )
            rm_dup_old = qs_df.drop_duplicates(
                subset=["ir_family_id"],
                keep="last"
            )
            ids_of_latest_cases = rm_dup_old["id"].tolist()
            return self.filter(id__in=ids_of_latest_cases)
        else:
            return qs

class GELInterpretationReport(models.Model):
    objects = GELInterpretationReportQuerySet.as_manager()

    ir_family = models.ForeignKey(
        InterpretationReportFamily, on_delete=models.CASCADE)
    archived_version = models.IntegerField(default=1)

    # TODO: add choices class for this based on spreadsheet
    status = models.CharField(max_length=200)
    updated = models.DateTimeField()

    sample_type = models.CharField(max_length=200, choices=(('cancer', 'cancer'),
                                                            ('raredisease', 'raredisease')))
    sample_id = models.CharField(max_length=200, null=True, blank=True)
    tumour_content = models.CharField(max_length=200, blank=True, null=True)

    max_tier = models.CharField(max_length=1, null=True)

gelweb/gel2mdt/templates/gel2mdt/add_new_attendee.html
<!--Copyright (c) 2018 Great Ormond Street Hospital for Children NHS Foundation
Trust & Birmingham Women's and Children's NHS Foundation Trust

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
{% extends 'gel2mdt/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block content %}
<div class="container-fluid" >
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                Add a new attendee
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                        <form method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button type="submit">Submit</button>
                          </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

gelweb/gel2mdt/templates/gel2mdt/audit.html
{% extends 'gel2mdt/base.html' %}
{% load static %}
{% block bokeh_head %}
<meta charset="UTF-8">
<script src="{% static 'js/bokeh-0.12.15.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/bokeh-0.12.15.min.css' %}">
{% if script %}
{{script|safe}}
{% endif %}
{% endblock %}
{% block content %}

{% if div %}
{{div|safe}}
{% else %}
<h1>Plotting Failed for Audits</h1>
{% endif %}

{% endblock %}

gelweb/gel2mdt/templates/gel2mdt/index.html
<!--Copyright (c) 2018 Great Ormond Street Hospital for Children NHS Foundation
Trust & Birmingham Women's and Children's NHS Foundation Trust

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
{% extends 'gel2mdt/base.html' %}
{% load bootstrap3 %}
{% load static %}


{% block content %}

{% if user.is_authenticated %}
<h2> Please select a portal </h2>

<div  class="container-fluid"  >
<div class="row">
    <div class="col-lg-6">
        <div class="thumbnail">
            <a href="/cancer-main">
                <img src="{% static 'figures/cancer.jpg' %}" alt="Cancer" style="width:100%;  height: 30%"></a>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="thumbnail">
            <a href="/rare-disease-main">
                <img src="{% static 'figures/rare-diseases.jpg' %}" alt="Rare Disease" style="width:100%; height: 30%" ></a>
        </div>
    </div>
</div>
</div>

    {%  else %}
    <div class="container">
    <div class="jumbotron">

    <h1>Welcome to GEL2MDT</h1>
        <p>To get started, please either {% bootstrap_button "Login" button_type="submit" button_class="btn-primary" href='/login' %}
            or
        {% bootstrap_button "Register" button_type="submit" button_class="btn-primary" href='/register' %} </p>
  </div>

</div>
    {% endif %}
{% endblock %}

gelweb/gel2mdt/templates/gel2mdt/messages.html
<!--Copyright (c) 2018 Great Ormond Street Hospital for Children NHS Foundation
Trust & Birmingham Women's and Children's NHS Foundation Trust

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

gelweb/gel2mdt/templates/gel2mdt/recent_mdts.html
<!--Copyright (c) 2018 Great Ormond Street Hospital for Children NHS Foundation
Trust & Birmingham Women's and Children's NHS Foundation Trust

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
{% extends 'gel2mdt/base.html' %}
{% load bootstrap3 %}
{% load static %}


{% block tabs %}

            <ul class="nav navbar-nav">
                        {% if sample_type == 'cancer' %}
                            <li><a href="{% url 'cancer-main' %}"><i class="fas fa-home"></i></span> Cases</a></li>
                            </ul>
                        {% elif sample_type == 'raredisease' %}
                            <li><a href="{% url 'rare-disease-main' %}"><i class="fas fa-home"></i></span> Cases</a></li>
                            </ul>
                        {% endif %}

                   <ul class="nav navbar-nav">
                       <li><a href="{% url 'start-mdt' sample_type=sample_type %}" ><i class="fas fa-comments"></i> Start MDT</a></li>
                        </ul>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'recent-mdt' sample_type=sample_type %}" ><i class="fas fa-history"></i> Recent MDTs</a></li>
                        </ul>
                   <ul class="nav navbar-nav">
                        <li><a href="{% url 'audit' sample_type=sample_type %}" ><i class="fas fa-tachometer-alt"></i> Audit</a></li>
                        </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'validation-list' sample_type=sample_type %}" ><i class="fas fa-check-circle"></i> Validation</a></li>
                        </ul>
{% endblock %}



{% block content %}
    {% load gel2mdt_extras %}
 <div  class="container-fluid"  >
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Recent MDT's
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-recent_mdt">

                    <thead>
                        <tr>
                            <th>MDT ID </th>
                            <th>Description</th>
                            <th>Date</th>
                            <th>Patients Discussed</th>
                            <th>Status</th>
                            <th>Creator</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for mdt in recent_mdt %}
                        <tr>
                            <td><a href="/mdt_view/{{mdt.id}}">{{mdt.id}}</a></td>
                            {% if mdt.description %}
                            <td>{{mdt.description}}</td>
                            {% else %}
                            <td></td>
                            {% endif %}
                            <td>{{mdt.date_of_mdt|date}}</td>
                            <td>{% for report_list in probands_in_mdt|get_item:mdt.id %}
                                    <a href="/proband/{{report_list.0}}"> {{ report_list.1}}</a>
                                {% endfor %}
                            </td>
                            <td>{{mdt.get_status_display}}</td>
                            <td>{{mdt.creator}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
 </div>
</div>
{% endblock %}